### ISSUE TITLE
Failed to import packages from hyperparameter_hunter

### ISSUE THREAD

**Issue by KleinXin** [HunterMcGushion/hyperparameter_hunter#214]
It is very strange that I could not import any packages from hyperparameter_hunter

I installed hyperparameter_hunter from github and wrote a script that has only three lines with name 'test.py' and the code is as below

#1 from hyperparameter_hunter import Environment, CVExperiment
#2 from hyperparameter_hunter import RandomForestOptPro, Real, Integer, Categorical

#3 print("test")

When I run "python test.py", nothing is shown on the screen. However, when the first two lines are commented, "test" is printted on the screen.

Anyone knows what is the problem?

**Comment by HunterMcGushion** [comment]
@KleinXin,

Thank you for the report. That's definitely a bug. I'm looking into a fix now, and I'll update you as soon as I have something!

**Comment by HunterMcGushion** [comment]
@KleinXin 

Can you try installing the `maint/pytest-version-conflict` branch to see if that takes care of the issue for you?

`pip install git+https://github.com/HunterMcGushion/hyperparameter_hunter.git@maint/pytest-version-conflict`

**Comment by KleinXin** [comment]
> @KleinXin
> 
> Can you try installing the `maint/pytest-version-conflict` branch to see if that takes care of the issue for you?
> 
> `pip install git+https://github.com/HunterMcGushion/hyperparameter_hunter.git@maint/pytest-version-conflict`

It's working now. thx!
