### ISSUE TITLE
Support usage as a black box optimizer of arbitrary function without any dataset.

### ISSUE THREAD

**Issue by KOLANICH** [HunterMcGushion/hyperparameter_hunter#58]

**Comment by HunterMcGushion** [comment]
Thanks for opening this, @KOLANICH. I think this could be doable by making some version of `optimization_core.BaseOptimizationProtocol` that doesn't need an `Environment` to function. Any chance you'd be interested in looking into this?

**Comment by KOLANICH** [comment]
>I think this could be doable by making some version of optimization_core.BaseOptimizationProtocol that doesn't need an Environment to function.

:+1:

>Any chance you'd be interested in looking into this?

There are chances, but I don't know how small they are. Currently I have no plans to make a PR, but I don't exclude this possibility.

Black box optimizer is needed because I use xgboost native crossvalidation which works with much less overhead than sklearn-like interface.

**Comment by HunterMcGushion** [comment]
Understood, thanks for letting me know. Ah I see. I haven't used the native XGBoost CV much, but I'll look into ways to work that in. Thanks for pointing it out!

**Comment by HunterMcGushion** [comment]
@KOLANICH, I may be missing your point, but would something like this suit your needs:

```python
import xgboost

env = Environment(
    train_dataset=get_breast_cancer_data(target='target'),
    root_results_path='HyperparameterHunterAssets',
    metrics_map=['roc_auc_score'],
    cross_validation_type=xgboost.cv,
    cross_validation_params=dict(),  # Kwargs for `xgboost.cv`, excluding `params` and `dtrain`
)
```

Then, upon detecting `cross_validation_type` of `xgboost.cv`, the `train_dataset` is converted to an `xgboost.DMatrix`.

```python
experiment = CrossValidationExperiment(
    model_initializer=XGBClassifier,  # This is ignored
    model_init_params=dict(objective='reg:linear', max_depth=3, n_estimators=100, subsample=0.5)
)
```

When an Experiment is created, if `model_initializer` is from XGBoost, and the `Environment`'s `cross_validation_type` is `xgboost.cv`, then the arguments are rearranged into the form expected by `xgboost.cv`:

```python
result = xgboost.cv(
    params=experiment.model_init_params,
    dtrain=env.train_dataset,  # (Converted to `xgboost.DMatrix`)
    **env.cross_validation_params
)
```

Then the results are still saved, and reused as learning material when performing optimization with the same `Environment` parameters.

I might be misunderstanding your point about functioning without a dataset, but is this kind of what you meant?

**Comment by KOLANICH** [comment]
>I may be missing your point, but would something like this suit your needs

Thank you for the examples, but I have built a framework around xgboost using optimizers in a black box way (here is [the example how I have plugged hyperopt there](https://github.com/KOLANICH/AutoXGBoost.py/blob/master/AutoXGBoost/hyperparamsOptimizers/hyperopt.py)) and setting all the params and preparing the dataset within it (don't use it for now, heavy refactoring is going on, the part wrapping optimizer is moving into a separate lib).

I definitely can use your approach with minimal changes, but I prefer to have access to a black box optimizer.

**Comment by HunterMcGushion** [comment]
I see. Your project is very interesting, thank you for sharing. However, since I'm more focused on long-term optimization by saving results, so they can be automatically reused every time optimization is started again, I'll respectfully close this issue. Good luck to you, and I look forward to any opportunities we may have to work together!
